console.log("Hello, TypeScript!");
console.log("This is a TypeScript script.");
console.log("TypeScript is a superset of JavaScript.");
console.log("TypeScript adds static typing to JavaScript.");
console.log("TypeScript is developed and maintained by Microsoft.");
console.log("TypeScript is open-source.");
console.log("TypeScript is used for large-scale applications.");
console.log("TypeScript is used by many companies.");
console.log("TypeScript is used by many developers.");
console.log("TypeScript is used for front-end and back-end development.");
console.log("TypeScript is used for web development.");
console.log("TypeScript is used for mobile development.");
console.log("TypeScript is used for desktop development.");
